### ISSUE TITLE
Repository structure

### ISSUE THREAD

**Issue by tarcieri** [RustCrypto/nacl-compat#1]
First question for this repo I think is what do we want to put in here?

Should we just move `crypto_box` in as a crate, or should we try to put together a more monolithic crate kind of like `ring-compat`?

Offhand I'm not sure what else would go in a `nacl-compat` library other than `crypto_box`. One option would be to pull together our existing crates which implement various NaCl algorithms into a monolithic, NaCl-like facade.

**Comment by newpavlov** [comment]
For now I will simply pull `crypto_box` to here. I think it could be nice to have a drop-in replacement for NaCl/libsodium (i.e. emulation of APIs provided by Rust wrappers). Maybe eventually even C API library implemented in pure Rust?

I plan to leave this repository generally to you, so feel free to modify it as you see fit.

**Comment by newpavlov** [comment]
It may be also feasible to implement some of our traits for wrapped NaCl/libsodium as done in `ring-compat`. Not sure about usefulness of such wrapper though. A better place for it could be one of 3rd party wrapper crates.

**Comment by tarcieri** [comment]
It seems we have an answer for my question: `crypto_secretstream`
