### ISSUE TITLE
crypto_secretbox Key: Zeroize on drop

### ISSUE THREAD

**Issue by threema-danilo** [RustCrypto/nacl-compat#154]
From what I can tell, the `Key` type is an alias for `GenericArray`. While we do set the `zeroize` feature for the dependency, this [only adds a zeroize method](https://github.com/fizyk20/generic-array/blob/master/src/impl_zeroize.rs), but it doesn't automatically call it on drop.

The key is only zeroized [when dropping the `SecretBox`](https://github.com/RustCrypto/nacl-compat/blob/a7f32e455273ed713535237727e78f7b6385b0c6/crypto_secretbox/src/lib.rs#L307-L311). But [when constructing a `SecretBox`](https://github.com/RustCrypto/nacl-compat/blob/a7f32e455273ed713535237727e78f7b6385b0c6/crypto_secretbox/src/lib.rs#L196-L202), the key is passed in by reference and is then dereferenced, causing it to be copied.

In contrast, the secret key in `crypto_box` [is not a type alias](https://github.com/RustCrypto/nacl-compat/blob/a7f32e455273ed713535237727e78f7b6385b0c6/crypto_box/src/secret_key.rs#L26-L31) but a wrapper type that [is zeroized on drop](https://github.com/RustCrypto/nacl-compat/blob/a7f32e455273ed713535237727e78f7b6385b0c6/crypto_box/src/secret_key.rs#L122-L126).

Am I missing something? If not, should a newtype be added for the key, which guarantees that the key material is zeroized on drop?

**Comment by tarcieri** [comment]
We accept all keys as references. You are responsible for how they are stored and zeroizing them, if you so desire.

> should a newtype be added for the key

How would that help? It just adds needless extra steps: you need to transform whatever source of bytes you have into an intermediate key newtype, then into a `SecretBox`. If anything, it would *force* you into making extra copies of the key, which would be bad.

You can construct a `&GenericArray` from `&[u8]` or `&[u8; N]` for an appropriate sized `N`, which avoids making an additional copy. The current constructor for that is `GenericArray::from_slice` for the former, and using `AsRef::as_ref` for the latter.

**Comment by threema-danilo** [comment]
> We accept all keys as references. You are responsible for how they are stored and zeroizing them, if you so desire.

The main point was: `Key` is a type (alias) from `crypto_secretbox`. All key-related types in `crypto_box` zeroize on drop. The secret box itself also zeroizes its copy of the key on drop. But not the key that was used to construct the secret box.

> How would that help? It just adds needless extra steps: you need to transform whatever source of bytes you have into an intermediate key newtype

That intermediate key type (although not a type alias) already exists, in the form of an alias to `GenericArray`. It would help in the sense that all key types from the `nacl-compat` library group would handle zeroizing the same way. I, as a user, would only need to zeroize my own types, but not types coming from `nacl-compat`.

**Comment by tarcieri** [comment]
> All key-related types in crypto_box zeroize on drop.

The `[u8; 32]` here is the analogous key type. We don't (and can't) `impl ZeroizeOnDrop` there.

https://docs.rs/crypto_box/latest/crypto_box/struct.SecretKey.html#method.from_bytes

Yes, there are `SecretKey` and `PublicKey` types, but these are wrappers for elliptic cure scalars and points, not byte arrays. They represent complex structures parsed from keys. Also it's a public key cryptosystem built on Diffie-Hellman, so it naturally requires a third step for encapsulating the result of combining the secret public keys.

> That intermediate key type (although not a type alias) already exists, in the form of an alias to GenericArray

We want to move to e.g. `&[u8; 32]` for that when const generics are sufficiently powerful enough. Arguably they are now.

I hope you understand the multitude of reasons why it isn't possible to impl `ZeroizeOnDrop` for `&[u8; 32]`.

The key has to come from somewhere, and it needs to be 32-bytes long. Adding a newtype which owns `[u8; 32]` that impls `ZeroizeOnDrop` is fairly pointless: you still need a `&[u8; 32]` to construct it, and if you care about zeroization, something still needs to take care of zeroizing *that*, wherever it comes from.

So all it would do is make an extra copy of key in memory, and while the owning struct could take care of zeroizing that, it still leaves the problem that you have a `[u8; 32]` sitting somewhere in memory that you constructed it from.

**Comment by threema-danilo** [comment]
I see, that makes sense! Thanks for your explanations.
