### ISSUE TITLE
PQC key exchange using kyber

### ISSUE THREAD

**Issue by shriphani** [RustCrypto/nacl-compat#172]
Would there be interest in a pqc crypto_box using kyber for the key exchange mechanism? It would require importing the pqcrypto crate which wouldn't be pure rust.

**Comment by tarcieri** [comment]
This library is intended for compatibility with NaCl algorithms. Unless it's in e.g. libsodium then it doesn't belong here.

There's a pure Rust implementation of ML-KEM (formerly Kyber) here: https://github.com/RustCrypto/KEMs/tree/master/ml-kem
