### ISSUE TITLE
API: PublicKey.as_bytes() vs SecretKey.to_bytes()

### ISSUE THREAD

**Issue by threema-danilo** [RustCrypto/nacl-compat#23]
The public key bytes can be accessed with `fn as_bytes(&self) -> &[u8; 32]` while the secret key bytes can be copied with `fn to_bytes(&self) -> [u8; 32]`. Is there a reason for this asymmetry?

If nothing speaks against it, I would propose to add an `as_bytes(&self) -> &[u8; 32]` method to `SecretKey` and to deprecate `to_bytes`. (The bytes can be copied by dereferencing the slice, if desired.) I'd be happy to submit a PR, if this proposal is accepted.

**Comment by tarcieri** [comment]
I assume you're talking about the `crypto_box` crate?

If so, that sounds fine.

**Comment by threema-danilo** [comment]
Yes, sorry. I should have clarified that 🙂
