### ISSUE TITLE
WASM Support?

### ISSUE THREAD

**Issue by zicklag** [RustCrypto/nacl-compat#37]
Hey folks, first off, these libraries look awesome! :star_struck: 

And you have such amazing explanations at the top of the docs for each one, so big thanks for that!

I just wanted to make sure that these libraries were intended to be usable if targeting the browser with WASM. I was able to compile it for `wasm32-unknown-unknown` it looks like, but for something so sensitive as crypto I wanted to make sure that it was intentionally supported before I just tried using it in the browser for my app.

**Comment by tarcieri** [comment]
We test builds of all of our crates on WASM targets in CI. We don't actually run tests on them yet though. It would be good to figure out a recipe for that.

To our knowledge there aren't particular problems you should encounter.

**Comment by zicklag** [comment]
Awesome, that's good enough for me for now. Thanks!
