### ISSUE TITLE
Release crypto_box v0.7.2 with fixed docs

### ISSUE THREAD

**Issue by newpavlov** [RustCrypto/nacl-compat#40]
The v0.7.1 release [does not enable](https://github.com/RustCrypto/nacl-compat/blob/crypto_box-v0.7.1/crypto_box/src/lib.rs#L185-L191) the `doc_cfg` feature, which causes [doc build failure](https://docs.rs/crate/crypto_box/0.7.1/builds/491318) on docs.rs.

**Comment by tarcieri** [comment]
We've landed a few other PRs since, so I cut a release including #30 and some typo fixups:

https://github.com/RustCrypto/nacl-compat/tree/crypto_box-v0.7.2

Changelog entry here: #43
